[tool.poetry]
name = "hyperiontf"
version = "0.3.5"
description = "Hyperion Testing Framework"
authors = ["Oleksiy Bondar <bondaroleksiyandriyovich@gmail.com>"]
license = "Apache 2.0 License"
readme = "README.md"

[tool.poetry.dependencies]
requests="^2.31.0"
python = "^3.11"
jsonschema = "^4.20.0"
selenium = "^4.18.1"
Appium-Python-Client = "^3.2.0"
playwright = "^1.41.2"
webdriver_manager="^4.0.1"
ply="^3.11"
opencv-python="^4.9.0.80"
opencv-python-headless="^4.9.0.80"
opencv-contrib-python="^4.9.0.80"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
